name: Build and Deploy to Production
on:
    push:
        branches:
            - staging
jobs:
    build:
        name: 👨‍🏭 build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@master
            - name: Setup Enviroment
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.0'
            - name: Install dependencies
              run: composer install --no-dev --no-progress --no-suggest --optimize-autoloader
            - name: 🚀 Deploy
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                server: ftp.atutracer.net
                username: ${{ secrets.FTP_STAGING }}
                password: ${{ secrets.FTP_PASSWORD }}
      
